export { R as Resolver, a as default, k as getExportsTarget, m as newResolver, s as setOffline } from './resolver-45c5386a.js';
import 'es-module-lexer';
import 'fs';
import 'mkdirp';
import 'buffer';
import 'path';
import 'process';
import 'url';
import 'crypto';
import 'sver';
import 'sver/convert-range';
